name-template: 'v$INPUT_VERSION'
tag-template: 'v$INPUT_VERSION'
categories:
  - title: 'Dependency updates'
    label: 'dependencies'
change-template: '- $TITLE (#$NUMBER @$AUTHOR)'
change-title-escapes: '\<*_&'
template: |
  ## Changes
  $CHANGES