name: Basics CD

on:
  release:
    types: [ published ]

jobs:
  publish:
    name: Publish Basics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b
      - name: Publish
        run: ./gradlew --no-daemon publish
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER }}
          MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}