name: Basics CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ basics-core ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2.4.0
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Grant gradlew execute permission
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew :${{ matrix.module }}:buildDependents
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./${{ matrix.module }}/build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests,${{ matrix.module }}