name: Basics CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [ basics-core ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2.4.0
        with:
          distribution: temurin
          java-version: 17
      - name: Grant gradlew execute permission
        run: chmod +x gradlew
      - name: Test with Gradle
        run: ./gradlew :${{ matrix.module }}:build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./${{ matrix.module }}/build/reports/jacoco/test/jacocoTestReport.xml
          flags: unittests,${{ matrix.module }}
  draftRelease:
    name: Create a draft release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2.4.0
        with:
          distribution: temurin
          java-version: 17
      - name: Grant gradlew execute permission
        run: chmod +x gradlew
      - name: Export Properties
        id: properties
        run: |
          PROPERTIES="$(./gradlew properties --console=plain -q)"
          VERSION="$(echo "$PROPERTIES" | grep "^versionString:" | cut -f2- -d ' ')"
          echo "::set-output name=version::$VERSION"
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: ${{ steps.properties.outputs.version }}
          prerelease: ${{ contains(steps.properties.outputs.version, 'alpha') || contains(steps.properties.outputs.version, 'beta') }}